# Generated by Django 5.1 on 2024-12-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='id_cliente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_empleado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
